### ISSUE TITLE
[Feature Request] add auto completion in zsh

### ISSUE THREAD

**Issue by zhengcan** [fluttertools/fvm#342]
I use the following alias in zsh:
```
alias flutter='fvm flutter'
alias dart='fvm dart'
alias pub='fvm dart pub'
```

Due to the lack of auto completion of fvm, zsh cannot show any suggestion when I'm typing commands.

**Comment by E-jarod** [comment]
I would like to add, that an oh-my-zsh plugin will be awesome, as it is the case for many plugins in the image below (including nvm)

![image](https://user-images.githubusercontent.com/57091681/133261097-3c7c53b2-8f42-4b79-9da1-d01174fbeefd.png)

**Comment by leoafarias** [comment]
@E-jarod if you can provide some more information to see if we can get a contributor for that would be helpful

**Comment by hotdang-ca** [comment]
I'd love to look at this one, @leoafarias

**Comment by leoafarias** [comment]
@hotdang-ca be my guest!

**Comment by leoafarias** [comment]
For anyone find this I suggest using https://fig.io, it already supports FVM

**Comment by kuhnroyal** [comment]
> For anyone finding this I suggest using [fig.io](https://fig.io), it already supports FVM

Noticed this the other day, nice!

**Comment by syohex** [comment]
https://github.com/zsh-users/zsh-completions/blob/master/src/_fvm

I wrote zsh completion of fvm. Please try it.
