### ISSUE TITLE
Needs to run `dart pub global activate fvm` everytime use `fvm global <version>` to change version [BUG]

### ISSUE THREAD

**Issue by raymondnexsoftech** [fluttertools/fvm#377]
**Describe the bug**
Everytime I run `fvm global <version>`, the command line will alert me that I need to update the path from "/Users/<User>/fvm/versions/<version>/bin" to "/Users/<User>/fvm/default/bin", even I already changed the path to default path.
And when I run fvm command after switch version, it always return error like "Can't load Kernel binary: Invalid kernel binary format version.", until I run `dart pub global activate fvm` to re-activate the version

**To Reproduce**

1. Go to terminal..
2. Run `fvm global stable`
3. Run `fvm list`, it will return error
4. Run `dart pub global activate fvm` and run `fvm list` will list all versions installed
5. Run `fvm global 2.2.3`
6. Run `fvm list`, it will return error
7. Run `dart pub global activate fvm` and run `fvm list` will list all versions installed

**Expected behavior**
Expect only run `fvm global <version>` and I can use fvm command normally

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

% fvm global 2.2.3
Flutter "2.2.3" has been set as global
However your "flutter" path current points to:

/Users/<User>/fvm/versions/stable/bin
to use global Flutter SDK through FVM you should change it to:

/Users/<User>/fvm/default/bin
% fvm global stable
Can't load Kernel binary: Invalid kernel binary format version.
Precompiling executable... (1.4s)
Failed to precompile fvm:main:
../../../.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/shell.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
/// {@canonicalFor prompt.prompt}
^
../../../.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/dartbin.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
/// Prefer using shell.
^
../../../.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/io/shared_stdin.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
// Copyright 2017, the Dart project authors.  Please see the AUTHORS file
^
../../../.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/shell_utils.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:convert';
^
../../../.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/user_config.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:io';
^
../../../.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/lines_utils.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:convert';
^
../../../.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/process_cmd.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:async';
^
../../../.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/prompt.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:convert';
^
../../../.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/shell.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:convert';
^
../../../.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/shell_environment.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:collection';
^

**Desktop (please complete the following information):**

- macOS: Version 12.0.1
- FVM Version: 2.2.4

**Comment by leoafarias** [comment]
@raymondnexsoftech can you run `fvm doctor` and post the output, also can you tell me between which Flutter versions you are switching in between?

**Comment by raymondnexsoftech** [comment]
I'm switch from flutter 2.2.3 to stable (2.5.3)
I use zsh to run terminal

When using flutter version 2.2.3:
```
% fvm doctor

No FVM config found:
/Users/<User>
Fvm will run the version in your PATH env: /Users/<User>/fvm/versions/2.2.3/bin/flutter

Configured env paths:
___________________________________________________

Flutter:
/Users/<User>/fvm/versions/2.2.3/bin/flutter

Dart:
/Users/<User>/fvm/versions/2.2.3/bin/dart

FVM_HOME:
not set
```
When I switch to stable, and then run `fvm doctor`:
```
% fvm global stable
Flutter "stable" has been set as global
However your "flutter" path current points to:

/Users/<User>/fvm/versions/2.2.3/bin
to use global Flutter SDK through FVM you should change it to:

/Users/<User>/fvm/default/bin
```
```
% fvm doctor       
Can't load Kernel binary: Invalid kernel binary format version.
/Users/<User>/.pub-cache/bin/fvm: line 15: pub: command not found
```

after run `dart pub global activate fvm`:
```
% dart pub global activate fvm
Package fvm is currently active at version 2.2.4.
Resolving dependencies... (1.5s)
+ args 2.3.0
+ charcode 1.3.1
+ cli_notify 0.0.3
+ cli_util 0.3.5
+ collection 1.15.0
+ console 4.1.0
+ date_format 2.0.4
+ fvm 2.2.4
+ io 1.0.3
+ meta 1.7.0
+ path 1.8.0
+ process_run 0.12.2+2
+ pub_semver 2.1.0
+ source_span 1.8.1
+ string_scanner 1.1.0
+ synchronized 3.0.0
+ term_glyph 1.2.0
+ tint 2.0.0
+ vector_math 2.1.1
+ yaml 3.1.0
Building package executables... 
Built fvm:main.
Installed executable fvm.
Activated fvm 2.2.4.
```
```
% fvm doctor

No FVM config found:
/Users/<User>
Fvm will run the version in your PATH env: /Users/<User>/fvm/versions/stable/bin/flutter

Configured env paths:
___________________________________________________

Flutter:
/Users/<User>/fvm/versions/stable/bin/flutter

Dart:
/Users/<User>/fvm/versions/stable/bin/dart

FVM_HOME:
not set
```

And after change back to 2.2.3:
```
% fvm global 2.2.3            
Flutter "2.2.3" has been set as global
However your "flutter" path current points to:

/Users/<User>/fvm/versions/stable/bin
to use global Flutter SDK through FVM you should change it to:

/Users/<User>/fvm/default/bin
```
```
% fvm doctor
Can't load Kernel binary: Invalid kernel binary format version.
Precompiling executable... (1.3s)
Failed to precompile fvm:main:
.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/shell.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
/// {@canonicalFor prompt.prompt}
^
.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/dartbin.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
/// Prefer using shell.
^
.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/io/shared_stdin.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
// Copyright 2017, the Dart project authors.  Please see the AUTHORS file
^
.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/shell_utils.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:convert';
^
.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/user_config.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:io';
^
.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/lines_utils.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:convert';
^
.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/process_cmd.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:async';
^
.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/prompt.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:convert';
^
.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/shell.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:convert';
^
.pub-cache/hosted/pub.dartlang.org/process_run-0.12.2+2/lib/src/shell_environment.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.13.
import 'dart:collection';
^
```

**Comment by nilsreichardt** [comment]
I have the same issue. I'm getting every time this message:
```
___________________________________________________


Update Available 2.2.2 → 2.2.6 
Run pub global activate fvm to update
Changelog: https://pub.dev/packages/fvm/changelog

___________________________________________________
```

I run `pub global activate fvm`, but after restart of the terminal, I'm still at version `2.2.0`

**Comment by leoafarias** [comment]
@nilsreichardt the reason for this issue is that I believe one of two things are happening.

The version of dart you are using to do the `pub global activate fvm` command does not support version 2.2.6 which to be honest dont think should be the case.

Another probability that you installed the standalone binary through brew or chocolatey, and therefore you should upgrade on those package managers.

**Comment by raymondnexsoftech** [comment]
@leoafarias how about my case?
According to your reply to nilsreichardt, it seems related to dart version, which in my system is using the dart included in flutter folder (/Users/<User>/fvm/versions/2.2.3/bin/dart)
Is it the reason that causing the error?

**Comment by leoafarias** [comment]
@raymondnexsoftech can you do `fvm doctor`, want to get a bit more context on it

**Comment by leoafarias** [comment]
Sorry @raymondnexsoftech you are correct. 

I would suggest using the standalone brew install, I have to take a look at this, but saw that the error message seems to be incorrect for some reason.

**Comment by leenjiru** [comment]
After taking a look at the FVM docs, it looks like you need to install dart by itself, separate to a flutter install.

To do that follow the instructions here: https://dart.dev/get-dart

Once you have done that you should be able to follow the rest of the FVM docs. 

Copy pasted from: https://stackoverflow.com/questions/66868564/command-not-found-pub-after-flutter-installation
