### ISSUE TITLE
[BUG] Intellij IDEA automatically resolves symlink to actual path

### ISSUE THREAD

**Issue by fzyzcjy** [fluttertools/fvm#391]
Hi thanks for the lib! However, Intellij IDEA automatically resolves symlink to actual path. For example, I enter `/path/to/my/app/.fvm/flutter_sdk`:

![image](https://user-images.githubusercontent.com/5236035/155053216-af2809e4-1609-4f94-a0c4-c9c5cb644b61.png)

And I click apply/ok:

![image](https://user-images.githubusercontent.com/5236035/155053241-1ecc8529-d7d5-488a-a999-4cd309c43d0f.png)

as you can see it auto resolves to actual path...

**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**

**To Reproduce**

1. Go to terminal..
2. Run `fvm use stable`...
3. Check...

**Expected behavior**

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop (please complete the following information):**

- FVM Version [e.g. 22]
- If Windows: Which Powershell are you using?

**Additional context**

**Comment by fzyzcjy** [comment]
bump

**Comment by leoafarias** [comment]
@fzyzcjy I believe this might be an issue with Android Studio. I think some time ago this behavior changed, where it resolves the symlink. I don't use Android Studio, but I wonder if there is per "project" configurations that can be added, as a local file similar to vscode.

If this is something you can do some research on we can keep this issue open, or it might be just a limitation on Android Studio

**Comment by fzyzcjy** [comment]
Well yes it may be a limitation of android studio :(
