### ISSUE TITLE
No SDKs have been installed yet. Flutter. SDKs installed outside of fvm will not be displayed.

### ISSUE THREAD

**Issue by erwinagpasa** [fluttertools/fvm#407]
Package fvm is currently active at version 2.2.6.
Resolving dependencies... (1.7s)
The package fvm is already activated at newest available version.
To recompile executables, first run `dart pub global deactivate fvm`.
Installed executable fvm.
Activated fvm 2.2.6.

When I hit **fvm list**

`No SDKs have been installed yet. Flutter. SDKs installed outside of fvm will not be displayed.`

**Comment by leoafarias** [comment]
The message is correct. FVM does not manage flutter versions installed outside of it, so you can continue to have the default “flutter” method

**Comment by erwinagpasa** [comment]
Thanks bro
