### ISSUE TITLE
intelliJ idea fvm flutter sdk automate

### ISSUE THREAD

**Issue by yagizdo** [fluttertools/fvm#417]
Hello. I started using the fvm. But I did not understand the part of choosing fvm sdk on intelliJ idea.

Every time I open a new project, will I choose the fvm sdk within that project? Is there no way to automate this?

**Comment by leoafarias** [comment]
@yagizdo it should work automatically when following the instructions on the docs Is that not the case?

**Comment by yagizdo** [comment]
> @yagizdo it should work automatically when following the instructions on the docs Is that not the case?

It says in the document that we need to choose the fvm version in the project. In this logic, won't the file of the previous project remain selected in another project? @leoafarias
