### ISSUE TITLE
[BUG] "Warning: Operand of null-aware operation..." when upgrading to Flutter 3.0.0 using fvm

### ISSUE THREAD

**Issue by Hixie** [fluttertools/fvm#418]
We're getting reports that people updating to Flutter 3.0.0 are seeing warnings when they try to run the template app, and the warnings mention code that does not exist any more in the Flutter framework, for example https://github.com/flutter/flutter/issues/103561.

I don't have any more context for this but figured you might want to know it was happening.

**Comment by leoafarias** [comment]
thank you @Hixie will take a look

**Comment by nilsreichardt** [comment]
I think this has nothing to do with `fvm`. I think this happens when the app is using packages which have not migrated to Flutter 3.0.
