### ISSUE TITLE
Can't use Flutter 3.0.0 or 3.0.1

### ISSUE THREAD

**Issue by matheus7mm** [fluttertools/fvm#428]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [X] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [X] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [X] Run `fvm doctor` if possible and add the output to the issue.

fvm doctor results:
FVM Version: 2.3.1
___________________________________________________

FVM config found:
___________________________________________________

Project: becare_app
Directory: /Users/matheus/development/projects/flutter/becare/develop/becare_app
Version: 3.0.1
Project Flavor: None selected
___________________________________________________

Version is currently cached locally.

Cache Path: /Users/matheus/fvm/versions/3.0.1
Channel: false
SDK Version: Need to finish setup. Run "fvm flutter doctor"

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: /Users/matheus/development/projects/flutter/becare/develop/becare_app/.fvm/flutter_sdk

Configured env paths:
___________________________________________________

Flutter:
/Users/matheus/development/tools/flutter/bin/flutter

Dart:
/opt/homebrew/bin/dart

FVM_HOME:
not set

**Describe the bug**
When I try to use Flutter 3.0.0 or 3.0.1 with fvm I have a strange error.

**To Reproduce**
1. Run `fvm install 3.0.1`
2. Run ` fvm use 3.0.1`
3. See the error. 

Error:
Building flutter tool...
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (2 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)
Command 'pub upgrade' still failed after 10 tries, giving up.
Project now uses Flutter [3.0.1]

**Expected behavior**
To use the Flutter 3.0.1.

**Logs**
Error using --verbose in the command:
[     0.002s] Version: 3.0.1 - already installed.
[     0.004s] Link is setup correctly
Building flutter tool...
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (2 tries left)
Could not find a file named "pubspec.yaml" in "/Users/matheus/.pub-cache/hosted/pub.dartlang.org/petitparser-5.0.0".
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)
Command 'pub upgrade' still failed after 10 tries, giving up.
[ 1m 08.093s] Link is setup correctly
Project now uses Flutter [3.0.1]

**Desktop (please complete the following information):**

- OS: macOS
- FVM Version: 2.3.1

**Additional context**
Other Flutter versions work fine, like 2.10.3. This is happening with 3.0.0 and 3.0.1.

**Comment by subzero911** [comment]
Since May... 😕
Seems like author abandoned this package.
Can anybody fork it and take care of FVM and upgrade dependencies to make it work with Flutter 3 and Dart 2.17?

**Comment by leoafarias** [comment]
@subzero911 Feel free to do a PR, and I will review it promptly, I am currently traveling... However I need very clear information about Dart vs, Flutter setup, as there have been packages that had a compatibility issues with Flutter 3.0, and we received a lot of noise about issues that were not corresponding to FVM.

**Comment by leoafarias** [comment]
@subzero911 I have updated the dependencies and dart version on version 2.4.0 let me know if that fixes the issue

**Comment by subzero911** [comment]
@leoafarias please update also Choco package.
It's still 2.3.1
![image](https://user-images.githubusercontent.com/12999702/177418063-3edf27b6-ea58-4a4a-9bb0-d006ec6a3c4e.png)

**Comment by leoafarias** [comment]
@subzero911 I have updated the chocolatey package, and is currently pending automated review on their end. Should be updated soon.

**Comment by subzero911** [comment]
@leoafarias Thanks! Now it works like charm.
