### ISSUE TITLE
[Feature Request] Use a local Flutter version

### ISSUE THREAD

**Issue by nilsreichardt** [fluttertools/fvm#429]
I didn't find any feature that solve this or an issue that mentions this request. If there is already a feature like this or an issue, feel free to close this ticket.

My goal is to make more contributions to the Flutter repo. Therefore, I have a local copy of the Flutter repo with my own changes. I would love to switch quick between my local Flutter repo and the real versions which I need for my projects.

Something like:
```
fvm use /Users/nils/Desktop/Projects/flutter-sdk
```

**Comment by leoafarias** [comment]
@nilsreichardt this feature is currently supported, you just have to fork the flutter-sdk version within the FVM cache directory.

https://fvm.app/docs/advanced/custom_version

**Comment by nilsreichardt** [comment]
Ahh, yeah this makes sense to locate them there! Thank you very much!
