### ISSUE TITLE
[Question] - How can i execute pub packages activates 

### ISSUE THREAD

**Issue by rodrigorahman** [fluttertools/fvm#431]
I need to run flutterfire commands to configure my project, and for that I need to run flutterfire.

Tried running "fvm dart pub global run flutterfire_cli:flutterfire configure"

But the console gets broken and I can't select the project.

How can I run flutterfire configure by FVM?

Thanks.

**Comment by tenhobi** [comment]
Hello, for globally activated packages, you usually also need the dart or flutter executables in your PATH. Ergo you have to set up manually one of the installed fvm versions as your global version is used for such cases. On Windows, for example, I added `C:\Users\<user>\fvm\versions\3.3.5\bin` to PATH variable.
