### ISSUE TITLE
Setting Android Studio As  Custom IDE Not Working

### ISSUE THREAD

**Issue by rahat14** [fluttertools/fvm#433]
While Trying to set Android studio as a custom ide in mac os is not working. After setting the android studio, going back to the project clicking the open custom it just open the finder app to the location but android studio don't open.

**Comment by leoafarias** [comment]
@rahat14 Is this issue meant for Sidekick?

**Comment by lizhuoyuan** [comment]
both fvm and sidekick

**Comment by leoafarias** [comment]
@lizhuoyuan please open it on Sidekick!
