### ISSUE TITLE
[BUG] Duplicate releases / no indication about different architectures on Apple Silicon

### ISSUE THREAD

**Issue by karniv00l** [fluttertools/fvm#437]
**Before creating a bug report please make check the following**

- [ ] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [ ] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [ ] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**

Since `Flutter` is being built for both `x64` and `arm64` platforms, we have more versions to choose from.
See releases.json: https://raw.githubusercontent.com/fluttertools/fvm/main/releases_macos.json

**To Reproduce**

1. On Apple M1/M2 go to terminal
2. Run `fvm releases`
3. See duplicate releases:

```bash
May 11 22  │ 3.0.0
May 11 22  │ 3.0.0
May 20 22  │ 3.0.1
May 20 22  │ 3.0.1
May 26 22  │ 3.1.0
May 26 22  │ 3.1.0
Jun 10 22  │ 3.0.2
Jun 10 22  │ 3.0.2
Jun 15 22  │ 3.1.0-9.0.pre
--------------------------------------
Jun 15 22  │ 3.1.0-9.0.pre     beta
--------------------------------------
Jun 22 22  │ 3.0.3
Jun 22 22  │ 3.0.3
Jul 1 22   │ 3.0.4
--------------------------------------
Jul 1 22   │ 3.0.4             stable
--------------------------------------
```

**Expected behavior**

Some indication of architecture for each version would be nice :) 

**Desktop (please complete the following information):**

- OS: `MacBook Pro 16, Apple M1 Max, macOS Monterey 12.4`
- FVM Version `2.3.1`

**Additional context**

Linked issue: https://github.com/fluttertools/sidekick/issues/246

**Comment by leoafarias** [comment]
@karniv00l This is not an issue on FVM, as FVM clones the repository and that is what gets installed. On FVM also this only affects the display, but installation will work correctly.

**Comment by leoafarias** [comment]
@karniv00l while implementing this, I hit a bit of a roadblock,  Is there a particular reason why you would like to display the architecture. FVM will install the ARM architecture if it's available. The reason I ask its because it's creating a lot of repeated data.

**Comment by karniv00l** [comment]
> Right now FVM is displaying only versions compatible with your architecture.

I think that's enough to close this issue, mine was just a suggestion, but it makes more sense to just hide the once that are not compatible ;)
