### ISSUE TITLE
[Feature Request] flutter and dart command without proxy

### ISSUE THREAD

**Issue by jeesang7** [fluttertools/fvm#438]
I think using fvm together with flutter and dart proxy commands is unnecessary.
Also, proxy command responses are not colored. #202 
The autocomplete function of the [ohmyzsh](https://ohmyz.sh) plugin cannot be used together.

Like [nvm](https://github.com/nvm-sh/nvm) or [pyenv](https://github.com/pyenv/pyenv), it would be better to separate the proxy command or use the command prompt display.
For example,
```
$ fvm use 3.0.4
$ (fvm) flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 11.6.4 20G417 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
...
```

Thanks for your attention. I’m looking forward to your reply or feedback.

**Comment by leoafarias** [comment]
@jeesang7 you are able to use FVM cached versions without the proxy. https://fvm.app/docs/guides/running_flutter#call-sdk-directly, however keep in mind that proxying might be needed when running scripts and tooling that are dependent on the Flutter configured version, as FVM injects the select cached version in the env vars of the process
