### ISSUE TITLE
[BUG] flutter does not work with version 3+

### ISSUE THREAD

**Issue by josefwilhelm** [fluttertools/fvm#447]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.
No FVM config found:
/Users/josefwilhelm/development/protofy/tchibo-utils
Fvm will run the version in your PATH env: /Users/josefwilhelm/fvm/default/bin/flutter

Configured env paths:
___________________________________________________

Flutter:
/Users/josefwilhelm/fvm/default/bin/flutter

Dart:
/usr/local/bin/dart

FVM_HOME:
not set

**Describe the bug**

Flutter version 3+ exists immediatly after command 'fvm flutter doctor' with 
`'sysctl -n hw.optional.arm64' returned unexpected output: '`

If I go down to v2.10.0 everything works fine

**To Reproduce**

1. Go to terminal..
2. Run `fvm global`...
3. select a flutter version 3+
4. run 'flutter doctor'
5. see error

**Expected behavior**
Flutter commands with version 3+ should work

**Logs**
Please provide the verbose logs by running `--verbose` after the command.
```

flutter doctor --verbose
'sysctl -n hw.optional.arm64' returned unexpected output: ''
```

**Desktop (please complete the following information):**

- OS: Mac 12.1
- FVM Version: 2.3.1

**Comment by leoafarias** [comment]
@josefwilhelm can you try with the latest version
