### ISSUE TITLE
[BUG] Unverified BreakPoint : Cannot debug  in flutter source code

### ISSUE THREAD

**Issue by Stitch-Taotao** [fluttertools/fvm#449]
Before I used fvm ,I can debug into flutter source code ,but after I use fvm , I can't step into flutter source code,and when I add breakpoint in source code , it show ' Unverified BreakPoint'.

I am sure I was use this version flutter code, because I can modified source code , and it worked,but breakpoint not.

It happended on Vscode!
![image](https://user-images.githubusercontent.com/26296915/179161637-835a704c-88c4-4ad4-9bca-d101b64a4740.png)

**Comment by leoafarias** [comment]
@Stitch-Taotao you need to make sure that vscode is using that version that is configured, most likely it is not, as FVM does not add any abstraction from an IDE perspective. Read this section to make sure its configured correctly https://fvm.app/docs/getting_started/configuration#vs-code

**Comment by Stitch-Taotao** [comment]
> @Stitch-Taotao you need to make sure that vscode is using that version that is configured, most likely it is not, as FVM does not add any abstraction from an IDE perspective. Read this section to make sure its configured correctly https://fvm.app/docs/getting_started/configuration#vs-code

I am sure  using the fvm version .

.vscode/settings.json
![image](https://user-images.githubusercontent.com/26296915/179658749-50120071-171e-4569-8294-279386474323.png)

.fvm folder (it auto generated by `fvm use 3.0.4`)
![image](https://user-images.githubusercontent.com/26296915/179658800-dbcb1c31-4159-4dd1-a213-1dda9241137f.png)

it's a new project ,so main is simple
![image](https://user-images.githubusercontent.com/26296915/179658946-1de171ee-1192-41d9-91fe-8a43a6efbb92.png)

then I just add a breakpoint and one line  print code in MaterailWidget's State 's build method:
![image](https://user-images.githubusercontent.com/26296915/179659175-8ef068a5-6cbc-42bd-b1fa-e31aa138a027.png)
when flutter run using debug button of F5 ,or even using fvm flutter run ,the breakpoint become invalid ,but the print code defintely executed!
![image](https://user-images.githubusercontent.com/26296915/179659560-4858e82e-94fa-407e-a4b7-60e31e4669fb.png)

You can create a new project using Vscode and test it like above process.

**Comment by leoafarias** [comment]
@Stitch-Taotao could it be because the files are removed on watcher?

**Comment by Stitch-Taotao** [comment]
> @Stitch-Taotao could it be because the files are removed on watcher?

Sorry,I don't understand your means.

**Comment by Stitch-Taotao** [comment]
I resolved this problem , Thank you.
https://github.com/Dart-Code/Dart-Code/issues/4071
