### ISSUE TITLE
[BUG] Cannot install fvm with Xcode 13.4.1

### ISSUE THREAD

**Issue by EugeneIOs** [fluttertools/fvm#456]
**Before creating a bug report please make check the following**

- [X] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [X] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [X] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [X] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
Cannot install fvm with latest Xcode 13.4.1. 

**To Reproduce**

1. Go to terminal on Mac with Xcode 13.4.1
2. Run 
```
brew tap leoafarias/fvm
brew install fvm
```
3. Check...
4. See error that fvm cannot be installed with Xcode 13.4.1 with error that Xcode 13.4 should be installed.

**Expected behavior**
fvm should be installed without errors

**Logs**
brew tap leoafarias/fvm
brew install fvm
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/rele
Already downloaded: /Users/eugene/Library/Caches/Homebrew/downloads/d5832359626d14f45648e5ed48a204756f83c64d6c229cd2bdd72cee0da08ff2--dartsdk-macos-x64-release.zip
==> Downloading https://github.com/fluttertools/fvm/archive/2.4.1.tar.gz
Already downloaded: /Users/eugene/Library/Caches/Homebrew/downloads/54b77538c3b1241d7203cf322d4c29f344917cfacab6f1f19203cff6dc2390e4--fvm-2.4.1.tar.gz
==> Installing fvm from leoafarias/fvm
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.4.

eugene ~ % xcodebuild -version
Xcode 13.4.1
Build version 13F100

**Additional context**

**Comment by xtuck** [comment]
+1

**Comment by acumenrev** [comment]
Same here. Cannot install with the latest Xcode 14.1
