### ISSUE TITLE
[Feature Request] Add this package to winget!

### ISSUE THREAD

**Issue by shinayser** [fluttertools/fvm#458]
Today `fvm`  is already downloadable from chocolatey, but `winget` is now the officially supported package manager for windows (much better, btw).

Would be amazing being able to download fvm from `winget `:)

**Comment by leoafarias** [comment]
@shinayser we don't plan to support any other package providers at this time.

**Comment by shinayser** [comment]
I understand!
Please just just keep in mind that `winget` is the official package manager that comes by default on all modern windows computers :)

**Comment by leoafarias** [comment]
@shinayser understood. I am not opposed to it, but FVM packaging depends heavily on https://github.com/google/dart_cli_pkg, so this implementation would have to be done on their side and we can roll to FVM.
