### ISSUE TITLE
fvm flutter env: bash\r: No such file or directory

### ISSUE THREAD

**Issue by cedteg** [fluttertools/fvm#459]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
fvm flutter can not execute 

**To Reproduce**

1. Go to terminal..
2. Run `brew install fvm`
3. Run `fvm global stable`
4. Run `fvm use stable`
5. Run `fvm flutter doctor`
6. Check...
7. See error
env: bash\r: No such file or directory

**Expected behavior**
flutter doctor content

**Logs**
Please provide the verbose logs by running `--verbose` after the command.
env: bash\r: No such file or directory

**Desktop (please complete the following information):**

- Mac OS 12.5 MacBook Pro M1 Pro
- FVM Version: 2.4.1

**Additional context**
fvm doctor --verbose

No FVM config found:
/Users/ctegenkamp
Fvm will run the version in your PATH env: /Users/ctegenkamp/fvm/default/bin/flutter

Configured env paths:
___________________________________________________

Flutter:
/Users/ctegenkamp/fvm/default/bin/flutter

Dart:
/opt/homebrew/Cellar/dart/2.17.6/libexec/bin/dart

FVM_HOME:
not set

**Comment by cedteg** [comment]
It seems like fvm is pulling the wrong architecture on my M1 Mac

If I manually replace the version with the arm64 version provided by flutter.dev it works

**Comment by cedteg** [comment]
@leoafarias problem is solved.

**Comment by wisnukurniawan** [comment]
hi @leoafarias I facing the same issue, but Im using Mac intel and already using flutter x64, when run `fvm install` or `fvm flutter doctor` I got `env: bash\r: No such file or directory`.

Another error when I run `fvm use 3.0.3` I got error 
```
Not a Flutter project. Run this FVM command at the root of a Flutter project or use --force to bypass this.
```

**Comment by mx1up** [comment]
> 3. if show error `env: bash\r: No such file or directory`, try `sudo find . -type f -exec dos2unix {} \;` for reference https://stackoverflow.com/a/63914652/5607894

this works, but is probably caused by a wrong git checkout wrt line endings. 
for example, on mac, set:
`git config --global core.autocrlf input`
then fvm remove and reinstall --> works

**Comment by myemuk** [comment]
Same to mee

**Comment by leoafarias** [comment]
@christophrichter2008 @myemuk most likely the SDK that fvm flutter is configured to is not installed. Go ahead and run `fvm install` and try to run the command again. Also if this works please open a ticket so I can do  better error handling on this.
