### ISSUE TITLE
Docker image outdated

### ISSUE THREAD

**Issue by jld3103** [fluttertools/fvm#461]
The docker image at https://hub.docker.com/r/leoafarias/fvm is very old and outdated. It looks like the pipeline only ran once: https://github.com/fluttertools/fvm/actions/workflows/deploy_docker.yml . Could you fix it and let it publish on every tag? The rules for when the pipeline should run are probably the broken part.

**Comment by leoafarias** [comment]
@jld3103 will try to take a look but might take some time, do you want to review and provide a PR?
