### ISSUE TITLE
[Feature Request] changing minSdkVersion, targetSdkVersion commands

### ISSUE THREAD

**Issue by shinriyo** [fluttertools/fvm#465]
## Before creating a feature request make sure the suggestion fit within our [principles](https://fvm.app/docs/getting_started/overview#principles)

**Is your feature request related to a problem? Please describe.**

Do you know the file?

`fvm/versions/3.0.5/packages/flutter_tools/gradle/flutter.gradle`

There are these lines.

```
    static int minSdkVersion = 16
    static int targetSdkVersion = 31
```

It is troublesome to find the file. I hope easy modification to change.

**Describe the solution you'd like**

Replace these versions in the file.

**Describe alternatives you've considered**

I want to change version commands like that.
`3.0.5` is version of Flutter.

```
fvm 3.0.5 android min 24
```

```
fvm 3.0.5 android target 24
```

Or, I will leave the exact command to you.

**Comment by leoafarias** [comment]
@shinriyo this file is on flutter_tools which is cached by `fvm`, but not in `fvm` itself. Most likely you will have to install a different flutter version.
