### ISSUE TITLE
[Feature Request] Can you provide YUM or source installation (instead of BREW)

### ISSUE THREAD

**Issue by zq0904** [fluttertools/fvm#466]
First of all, thank you for your contribution to this project!
Can you provide YUM or source installation
I am trying to install FVM in Linux for multi-version management of Flutter
But I can only use BREW install FVM and the BREW installation is extremely ugly

**Comment by zq0904** [comment]
> First of all, thank you for your contribution to this project! Can you provide YUM or source installation I am trying to install FVM in Linux for multi-version management of Flutter But I can only use BREW install FVM and the BREW installation is extremely ugly

I'm new to Linux
I just want to MAKE it easy to install the complete function but BREW installation is extremely ugly

**Comment by leoafarias** [comment]
@zq0904 We currently don't plan on supporting other installation methods, we use `cli-pkg` to create the build process so any, improvements and support of the platform would have to be supported by them. https://github.com/google/dart_cli_pkg.

**Comment by zq0904** [comment]
> @zq0904 We currently don't plan on supporting other installation methods, we use `cli-pkg` to create the build process so any, improvements and support of the platform would have to be supported by them. https://github.com/google/dart_cli_pkg.

Thank you for your answer
I am currently using (Flutter Pub Global Activate FVM in this way) although I need to install Fluttre globally once but I have no choice

Some other suggestions:
1. Can you use pure SH instead of existing FVM like NVM (installation will be easier)
2. Chinese users FVM install XXX is very slow, can you provide environment variables to specify the agent to solve this problem like NVM (currently I use other ways to download the installation package and then manually decompress it in ~/ FVM /versions this works)
3. In the Docker environment, FVM_HOME= XXX /. Pub-cache is used to set PATH=$PATH:$FVM_HOME/bin. Unfortunately, FVM_HOME is the cache directory of the version, which makes it take me a long time to rectify the problem Would it be better to provide an environment variable like FVM_CACHE_DIR if you think it is reasonable

**Comment by leoafarias** [comment]
1 - I believe you either have to use the compiled binaries or it will have to use pub global.
2 - I believe this is already implemented here https://fvm.app/docs/getting_started/configuration#different-flutter-repo, you can change the flutter repo to a different one.
3 - Could you make a PR for this so I can review?

**Comment by leoafarias** [comment]
We will had and close this issue. Please open a new issue addressing my comments if needed.
