### ISSUE TITLE
[Feature Request] Project initialization command

### ISSUE THREAD

**Issue by pastre** [fluttertools/fvm#467]
**Is your feature request related to a problem? Please describe.**
Manually creating a config file is prone to failure. 

**Describe the solution you'd like**
Create command to generate the config file using the CLI: `fvm init`. That command generate an `fvm.json` file in the current directory and FVM would look for that file to setup an environment. If the file doesn't exist, the behavior is the same as what we have today

**Describe alternatives you've considered**
Improving examples and docs

**Additional context**
This would work very similarly to `npm init` or `pipenv install (when project is not yet initialized)`. In the scope of this issue, we would have a `fvm.lock` file to lock FVM versions

**Comment by pastre** [comment]
I'd be very happy to implement this CLI, as long as the community is ok with it

**Comment by leoafarias** [comment]
@pastre what configuration would be within this file? The version pinning is handled automatically already.

**Comment by pastre** [comment]
@leoafarias you're right! This feature would only create a `.fvm` folder from CLI then :)

**Comment by leoafarias** [comment]
@pastre not sure if there is an issue, as this is also created when you pin a version through the `fvm use` command

**Comment by pastre** [comment]
@leoafarias Wait, fvm use will generate the .fvm folder?

**Comment by leoafarias** [comment]
Yes, that configuration is only used when is needed. If it's not being created then that's a bug

**Comment by pastre** [comment]
Got it, there's no issue there indeed! We could improve the docs and make that clearer. Other tools use `init` instead of `use`. Thanks for your time @leoafarias and for the awesome project! Will be happy to help with anything :)
