### ISSUE TITLE
[BUG] Problem on mac Ventura

### ISSUE THREAD

**Issue by mrabdulrrahimklis** [fluttertools/fvm#470]
**Before creating a bug report please make check the following**

- [ ] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [ ] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [ ] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
As I update on MacOS Ventura I get issue on that as I get issue for switching some versions and installing.

**To Reproduce**

1. Go to terminal..
2. brew tap leoafarias/fvm
3. brew install fvm
4. You will get this errors
<img width="1402" alt="Screenshot 2022-09-21 at 17 26 55" src="https://user-images.githubusercontent.com/7759870/191545987-37fa2e5c-1bc7-469c-9c40-67ae96623a43.png">

To have working fvm in terminal. 
I was working with them before and it works fine and as I update on Mac OS Ventura I get this errors.

**Comment by kuhnroyal** [comment]
This is a brew problem and has nothing to do with fvm. And the solution is written in your screenshot, just read it and fix it.

**Comment by mrabdulrrahimklis** [comment]
It's not an issue with brew. Also, I read it and do it but doesn't work.
