### ISSUE TITLE
why does FVM use/install a different Dart version ?

### ISSUE THREAD

**Issue by ajonno** [fluttertools/fvm#473]
Strange thing happened today. I installed/used 3.1.0 of Flutter via FVM:
```fvm use 3.1.0```
that worked fine.

then when i went to run the Flutter project, it threw an error saying the Dart SDK was wrong. Specifically this:
```
The current Dart SDK version is 2.18.0-44.1.beta.

Because mobile requires SDK version >=2.18.0 <3.0.0, version solving failed.
pub get failed (1; Because mobile requires SDK version >=2.18.0 <3.0.0, version solving failed.)
```

I'm like where the hell did that beta version of Dart come from?? Then I tracked it down to the /dart-sdk folder inside of the .fvm folder used by the given Flutter project.

Why is this version of Dart sitting in that /cache folder ?
How can I get rid of it so that the app uses the latest stable version of Dart ? (2.18.0)

<img width="706" alt="image" src="https://user-images.githubusercontent.com/3005269/191919441-7bb7914f-b0f4-4a82-9eb2-164bddad7a9b.png">

**Comment by leoafarias** [comment]
@ajonno The version is correct, what happens is the  parameter for the Dart SDK on pubspec, doesn't meet the constraints, maybe its the Beta flag.. try lowering the constraints to 2.17, and that might work.
