### ISSUE TITLE
Can Activate FVM 2.4.1 [BUG]

### ISSUE THREAD

**Issue by msarkrish** [fluttertools/fvm#475]
**Before creating a bug report please make check the following**

- [ ] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [ ] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**

**To Reproduce**

1. Go to terminal..
2. Run `dart pub global activate fvm`...
3. Check...

**Expected behavior**
I'm trying to upgrade fvm from 2.3.1 to 2.4.1 , but after running activate command its again have 2.3.1 version

C:\Users\krish>fvm doctor

No FVM config found:
C:\Users\krish
Fvm will run the version in your PATH env: null

Configured env paths:
___________________________________________________

Flutter:

Dart:
C:\dart-sdk\bin\dart.exe

FVM_HOME:
not set

**Desktop (please complete the following information):**

- OS: [Windows]
- FVM Version [2.3.1]
- If Windows: Which Powershell are you using?
CMD

**Comment by leoafarias** [comment]
I believe the version of dart installed its not compatible with FVM 2.4.1 so it installs the most compatible version. I suggest installing through chocolatey and that should solve this problem.
