### ISSUE TITLE
Whether an image can be provided for fvm install

### ISSUE THREAD

**Issue by zq0904** [fluttertools/fvm#476]
## The original
I'm a Chinese user so you know

## Just like nvm
```
  NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist nvm install 4.2
```

**Comment by leoafarias** [comment]
@zq0904 you might be looking for this https://fvm.app/docs/getting_started/configuration#different-flutter-repo

**Comment by zq0904** [comment]
> @zq0904 you might be looking for this https://fvm.app/docs/getting_started/configuration#different-flutter-repo

Thank you! That solved my problem
