### ISSUE TITLE
Installing a specific revision does not work

### ISSUE THREAD

**Issue by Wissperwind** [fluttertools/fvm#477]
Hi,

I would like to use a verry new flutter version. For example 3.4.0-37.0.pre.
But fvm provides only 3.4.0-17.2.pre
I looked in the doku and found that it is possible to install with a git commit id. So I tried to install 35afe1b what is the commit ID from 3.4.0-37.0.pre. But that does not work. It said the branch could not be found in upstream origin.
When are new versions added to fvm and why can't I install every version in https://github.com/flutter/flutter/tags?

**Comment by leoafarias** [comment]
@Wissperwind the version tags are provided by this Flutter Releases URL https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json, I believe, if you can describe more info on the error, I will be able o check it.

**Comment by Wissperwind** [comment]
So only the releases in your link can be installed via fvm? I think it would be better if one can also test verry new versions. So it would be handy to be able to install all versions with a tag via fvm. See the versions in my link.
just try `fvm install 3.4.0-37.0.pre` and you see the problem.

**Comment by leoafarias** [comment]
@Wissperwind you can also install specific commits. But I believe its not easy to identified non-tagged versions.
