### ISSUE TITLE
[QUESTION] Adjust linting to the flutter version in use by fvm

### ISSUE THREAD

**Issue by agonzalezpuerta** [fluttertools/fvm#479]
First of all thank you for the excellent tool that FVM is.

Is there any way to set FVM such that flutter_lints picks up the version that is in use?

Bonus Question: Which version are used by the linter? global, active or the external SDK?

Thank you!

**Comment by leoafarias** [comment]
@agonzalezpuerta I believe the linter is used on a per-project basis since its a dev_dependency on the project itself. Not sure if it has anything related to the Flutter version itself unless there is some compatibility issue

**Comment by agonzalezpuerta** [comment]
Thanks for the answer @leoafarias,
It seems like you are right about the linter using the per-project SDK. I've done a bit more research, and the issue seems to occur when you have multiple Flutter projects in your VS Code workspace. Opening one project at a time allows VS Code to recognize the SDK defined by FVM correctly (allowing for correct linting and builds). I believe the issue can be closed. Thanks!
