### ISSUE TITLE
[BUG]Could not install 3.3.7

### ISSUE THREAD

**Issue by SheepYang1993** [fluttertools/fvm#481]
```fvm install 3.3.7
Flutter "3.3.7" is not installed.

Installing version: 3.3.7...
Cloning into 'F:\fvm\versions\3.3.7'...
remote: Enumerating objects: 407851, done.        
remote: Counting objects: 100% (45/45), done.        
remote: Compressing objects: 100% (44/44), done.
remote: Total 407851 (delta 8), reused 1 (delta 1), pack-reused 407806        
Receiving objects: 100% (407851/407851), 217.60 MiB | 3.80 MiB/s, done.
Resolving deltas: 100% (311021/311021), done.
Updating files: 100% (6483/6483), done.
HEAD is now at e99c9c7cd9 Update Engine revision to 857bd6b74c5eb56151bfafe91e7fa6a82b6fee25 for stable release 3.3.7 (#114456)

Could not install 3.3.7

Please run command with  --verbose if you want more information```

**Comment by zejnir** [comment]
Tried with administrator privileges, doesn’t work. Any updates? I'm on version 3.3.9

**Comment by leoafarias** [comment]
@zejnir please run the same command with the `--verbose` flag

**Comment by leoafarias** [comment]
@zejnir please open another issue with the `--verbose` flag

**Comment by zejnir** [comment]
@leoafarias Thanks for fast response. I already solve the problem, I had problem with .fvm directory in my project. I erase folder and I run "fvm install".

**Comment by SheepYang1993** [comment]
> @leoafarias Thanks for fast response. I already solve the problem, I had problem with .fvm directory in my project. I erase folder and I run "fvm install".

Yes, I executed the "fvm use 3.7.0" command on Mac OS, and then executed the "fvm global 3.7.0" command on Windows. The error "Could not install 3.7.0" will be reported. Finally, I deleted the. fvm folder, and then executed the command successfully.
