### ISSUE TITLE
Automatically update stable

### ISSUE THREAD

**Issue by rhalff** [fluttertools/fvm#482]
When I run `fvm use stable` stable is not automatically updated to the latest stable version if it has been previously checked out.

I'll have to do something like `fvm flutter upgrade` to actually pull the latest stable version.

If the flutter version is set to `stable` I would expect it to always be the latest stable version and thus automatically update itself if this not the case.

I haven't checked, but I assume the same counts for `beta` and `dev`.

**Comment by leoafarias** [comment]
@rhalff That is a good suggestion, however this will probably not be implemented as it changes the expected behavior of the Flutter CLI, and the dev should be explicit about when upgrading..
