### ISSUE TITLE
[BUG] jenkins detects succsessful fvm build not as succsessful

### ISSUE THREAD

**Issue by Wissperwind** [fluttertools/fvm#483]
Hi,

I try to include a flutter fvm build in jenkins.
The build works. But jenkins does check the environment variable %ERRORLEVEL% after the build. Aparrentely it is not zero despite the succsessful build. So the jenkins build fails.
Could you please check the return values of fvm and set it to something jenkins interpretes ans good if the build is succsessful?

**Comment by leoafarias** [comment]
@Wissperwind Its not clear what the issue is, or how to replicate it. I will probably need a reproducible example, and very detailed logs, as I don't use Jenkins. 

FVM passes the environment variables down the flutter command

**Comment by jnschulze** [comment]
I have the same issue in Azure DevOps.

`fvm install`, for example, seems to complete successfully according to its output
```
Flutter 3.7.0-1.4.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 686fe913dc (8 days ago) • 2023-01-10 16:14:01 -0800
Engine • revision ac5c83dd5f
Tools • Dart 2.19.0 (build 2.19.0-444.4.beta) • DevTools 2.20.0
```

The `$LASTEXITCODE` is `-1073741819` (0xC0000005 -> access violation), however.

**Comment by jnschulze** [comment]
I was able to track the issue down.

The crash occurs when [_runCmd calls `switchLineMode` after running the command](https://github.com/fluttertools/fvm/blob/a326fa2467aceaecba282b9b1c9bd6fdb68a74f5/lib/src/utils/commands.dart#L130). 

Further investigation showed that the actual crash happens in [`stdioType` from `dart:io`](https://github.com/dart-lang/sdk/blob/78a9f52544269816877a945c1ddea6e0bcb4b72f/sdk/lib/io/stdio.dart#L421) (which is used by [`io.stdin.hasTerminal`](https://github.com/fluttertools/fvm/blob/ae7357632c45d9080faf2b924167e6001e17f741/lib/src/utils/logger.dart#L86)).

I was able to work around that issue by caching `ConsoleController.isTerminal` (see https://github.com/fluttertools/fvm/pull/495)
