### ISSUE TITLE
[BUG] SHA256 error when install by brew

### ISSUE THREAD

**Issue by FantaZZ** [fluttertools/fvm#496]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/5322276/215842928-ab413420-5b01-4b36-9981-8afecd75d588.png">

**Comment by azevedorafael** [comment]
I'm getting the same error here.

**Comment by macelangelo** [comment]
See:
https://github.com/leoafarias/homebrew-fvm/issues/8

https://github.com/leoafarias/homebrew-fvm/issues/6#issuecomment-1410818648

Github made a change to how the archives were generated, which they rolled back. 
BUT, not before other devs reported the issue and the fvm brew formula was changed.

I have a PR to change it back.

**Comment by leoafarias** [comment]
Merged
