### ISSUE TITLE
[Question] why is fvm no longer recommended for global flutter version control?

### ISSUE THREAD

**Issue by rodrigorahman** [fluttertools/fvm#497]
saw in the documentation that now FVM is no longer globally supported and I would like to know the main reason? Because, in my opinion, it made the transition between projects much easier, not having to change any internal configuration or even the way to run the commands inside the project

**Comment by leoafarias** [comment]
@rodrigorahman you can read more about it here https://github.com/fluttertools/fvm/discussions/469
