### ISSUE TITLE
[BUG] `fvm releases` `dev` channel updates not regognized

### ISSUE THREAD

**Issue by zoechi** [fluttertools/fvm#499]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**

**To Reproduce**

1. Go to terminal..
2. Run `fvm releases`
3. Check...
```
--------------------------------------
Apr 13 22  │ 2.13.0-0.1.pre    dev
--------------------------------------
```
4. See the date. It wasn't updated since almost a year

**Expected behavior**
`dev` is the most active channel and should not be on a date older than a few days

I guess the `dart-lang/sdk` repo changed the default branch from `master` to `main` and since then the `dev` channel didn't recognize updates anymore because it's looking on the old branch.

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop (please complete the following information):**

- OS: `Linux Dev 5.15.89-1.fc32.qubes.x86_64 #1 SMP Fri Jan 20 21:34:55 CET 2023 x86_64 GNU/Linux`
- FVM Version: `2.4.1`
- I'm using Nushell

**Additional context**

**Comment by leoafarias** [comment]
@zoechi the dev channel has been retired
https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels
