### ISSUE TITLE
[Feature Request] Implement short hand commands for install and list options

### ISSUE THREAD

**Issue by gonzalogauto** [fluttertools/fvm#502]
## Before creating a feature request make sure the suggestion fit within our [principles](https://fvm.app/docs/getting_started/overview#principles)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As an FVM user I want to have the option to list the available versions by using a short hand command like `ls` instead of `list`. Same when I want to install a new version, it will be nice to have a `i` command.

With those changes users can list the available versions by running `fvm ls` and install new version by using `fvm i X.X.X`)

**Describe alternatives you've considered**
#N/A

**Additional context**
#N/A

Thanks for mantain this awesome tool 😄 !!

**Comment by leoafarias** [comment]
@gonzalogauto if you would like to do a PR, I will review, I believe command_runner, has that feature called `aliases`, https://pub.dev/documentation/args/latest/command_runner/Command/aliases.html

**Comment by gonzalogauto** [comment]
> @gonzalogauto if you would like to do a PR, I will review, I believe command_runner, has that feature called `aliases`, https://pub.dev/documentation/args/latest/command_runner/Command/aliases.html

I can do that 😄 Yes, it can be done with aliases in a simple steps. Happy to be able to contribute to this great tool 😄 !! I will create a PR soon
