### ISSUE TITLE
in windows 11,when I run fvm use 3.7.7 throw error about " Seems you don't have the required permissions,FVM requires to run as an administrator or turn on developer mode: https://bit.ly/3vxRr2M"[BUG]

### ISSUE THREAD

**Issue by guuguo** [fluttertools/fvm#506]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
I run flutter use 3.7.7 in my flutter project.
throw error.

fvm doctor result:
```

FVM Version: 2.4.1
___________________________________________________

FVM config found:
___________________________________________________

Project: GuuguoReader
Directory: E:\guuguo\dev\flutter\GuuguoReader
Version: stable
Project Flavor: None selected
___________________________________________________

Version is currently cached locally.

Cache Path: C:\Users\Admin\fvm\versions\stable
Channel: true
SDK Version: 3.7.7

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: E:\guuguo\dev\flutter\GuuguoReader\.fvm\flutter_sdk


Configured env paths:
___________________________________________________

Flutter:
C:\Users\Admin\fvm\versions\3.7.7\bin\flutter.bat

Dart:
C:\Users\Admin\fvm\versions\3.7.7\bin\dart.bat

FVM_HOME:
not set
```

In fact, I have **turned on the developer options**, and running in powershell with administrator privileges is the same。
<img width="951" alt="image" src="https://user-images.githubusercontent.com/12984352/223902889-ac4fb539-27c2-4cf8-85b8-11f85b528a53.png">

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/12984352/223901709-38750ff4-508e-4dd0-90aa-4c4483684888.png">

**To Reproduce**

1. Go to terminal..
2. Run `fvm use 3.7.7`...
3. Check...

**Expected behavior**
changed fvm version to 3.7.7 in my project

**Logs**
```
PS E:\guuguo\dev\flutter\GuuguoReader> fvm use 3.7.7 --verbose
[     0.043s] Version: 3.7.7 - already installed.
[     0.053s] FileSystemException: Cannot create link to target 'C:\Users\Admin\fvm\versions\stable', path = 'E:\guuguo\dev\flutter\GuuguoReader\.fvm\flutter_sdk' (OS Error: 当文件已存在时，无法创建该文件。
, errno = 183)
[     0.053s] Usage Exception: Seems you don't have the required permissions on C:\Users\Admin\fvm On Windows FVM requires to run as an administrator or turn on developer mode: https://bit.ly/3vxRr2M
```

**Desktop (please complete the following information):**

- OS: [win10 and win11](I tried update win10 to win11，The error still exists )
- FVM Version [2.4.1]
- If Windows: Which Powershell are you using?
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  963
```

**Additional context**
Help me

**Comment by gvdhpinilla** [comment]
any solution?

**Comment by guuguo** [comment]
> any solution?

no,I am now stopping using fvm on Windows and using the original version of Flutter instead.

**Comment by leoafarias** [comment]
FVM needs permission to write to its directory, the error describes the solution of the problem.

**Comment by ruolunhui** [comment]
我的原因是将存放flutter版本的d盘所有数据，移动到别的盘符，格式化d盘之后再从备份数据还原到d盘之后就有问题，只需要把原理的flutter版本的上级目录删除，再用fvm重新下载不同版本就行
