### ISSUE TITLE
[BUG] Fvm command is not working on a particular project

### ISSUE THREAD

**Issue by t-bolt** [fluttertools/fvm#507]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
When i try to run any flutter command: <pre>fvm use 2.10.5 </pre>i get an error.

**To Reproduce**

1. Go to terminal..
2. Run `fvm use stable`...
3. Check...

**Expected behavior**

**Logs**
When i add the --verbose flag, i get the following:
<pre>[     0.008s] <font color="#171421"><b>Version: 2.10.5 - already installed.</b></font>
[     0.014s] <font color="#171421"><b>FileSystemException: Cannot create link to target &apos;/home/sobuur/fvm/versions/2.10.5&apos;, path = &apos;/home/sobuur/StudioProjects/project_name/.fvm/flutter_sdk&apos; (OS Error: File exists, errno = 17)</b></font>
[     0.014s] <font color="#171421"><b>Usage Exception: Seems you don&apos;t have the required permissions on /home/sobuur/fvm </b></font>

<font color="#C01C28">Could not install 2.10.5</font>

Please run command with  --verbose if you want more information
</pre> 

**Desktop (please complete the following information):**

- FVM Version [e.g. 22]
- If Windows: Which Powershell are you using?

**Additional context**
Running:
<pre>fvm doctor</pre>
Produces the output:
<pre>FVM Version: 2.4.1
___________________________________________________

<font color="#2AA1B3">FVM config found:</font>
___________________________________________________

Project: project_name
Directory: /home/sobuur/StudioProjects/project_name
Version: 2.10.5
Project Flavor: None selected
___________________________________________________

<font color="#2AA1B3">Version is currently cached locally.</font>

Cache Path: /home/sobuur/fvm/versions/2.10.5
Channel: false
SDK Version: 2.10.5

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: /home/sobuur/StudioProjects/project_name/.fvm/flutter_sdk

<font color="#2AA1B3">Configured env paths:</font>
___________________________________________________

Flutter:
/snap/bin/flutter

Dart:
/home/linuxbrew/.linuxbrew/bin/dart

FVM_HOME:
not set
</pre>

**Comment by leoafarias** [comment]
@t-bolt sorry for the delay on this. It seems that you do not have write permission on the direction for FVM

**Comment by t-bolt** [comment]
@leoafarias it's cool.
do i have to enable write permission for each project?

**Comment by leoafarias** [comment]
The directory of the project and the cache directory for fvm

**Comment by t-bolt** [comment]
Okay great.
Thank you for your time
