### ISSUE TITLE
[BUG?] Dart runtime version is not in sync with the global version of Flutter

### ISSUE THREAD

**Issue by mrdc** [fluttertools/fvm#509]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
When I set flutter global version via `fvm global 3.7.7`, then build an app and check Platform.version inside running app I see that Dart runtime version is outdated and not in sync with flutter.

**To Reproduce**

1. Install `Dart SDK version: 2.17.6` via `brew`
2. Use `fvm 2.4.1`
3. `fvm install 3.7.7`
4. `fvm global 3.7.7`
5. Add add `import 'dart:io' show Platform;` and `print($Plantform.version)` to the app (`main.dart`)
6. Build an app inside VS Code or Xcode
7. Check print($Plantform.version) to see that Dart runtime inside the app is not in sync with the global version of flutter

**Expected behavior**
When setting flutter global, the corresponding Dart SDK version should be used

**Logs**
```
~ % fvm doctor
No FVM config found:
/Users/admin
Fvm will run the version in your PATH env: /Users/admin/fvm/default/bin/flutter
Configured env paths:
___________________________________________________
Flutter:
/Users/admin/fvm/default/bin/flutter
Dart:
/usr/local/bin/dart
FVM_HOME:
not set

fvm list
Cache Directory:  /Users/xxxxxx/fvm/versions

3.7.7 (global)
3.0.5
2.10.5
2.8.1
2.5.3


~ % flutter --version
Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (13 days ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1

~ % dart --version
Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0000) on "macos_x64"

Plantform.version inside an app shows this:
2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "ios_x64"

~ % fvm dart --version
Dart SDK version: 2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "macos_x64"
```

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Dart SDK (installed via brew)
```
~ % dart --version
Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0000) on "macos_x64"
```
- FVM Version 
```
~ % fvm --version
2.4.1
```

**Comment by mrdc** [comment]
Looks like a bug: in build logs in Xcode I see "export FLUTTER_ROOT\=/Users/xxxxxxx/fvm/versions/2.10.5"
But 3.7.7 is selected globally:
```
fvm list
Cache Directory:  /Users/xxxxxx/fvm/versions
3.7.7 (global)
3.0.5
2.10.5
2.8.1
2.5.3
```
and 
```
~ % flutter --version
Flutter 3.7.7
```

**Comment by mrdc** [comment]
> Well, FVM has nothing to do with your XCode config. This is a problem in your environment. You need to figure out how the export got there and update it.

Env points to `/Users/xxxxxxx/fvm/versions/2.10.5`, so it's related to fvm, because I haven't made any new envs for flutter and no other software was able to do it as well. Just curious how it happened.

**Comment by kuhnroyal** [comment]
I don't think FVM manipulates the Env at all, so your `FLUTTER_ROOT` comes from somewhere else. Maybe Flutter sets it, not sure. You should try running `fvm flutter build ios` maybe something get's updated.

**Comment by mrdc** [comment]
Using 
```
flutter clean
flutter pub cache clean
flutter pub get
flutter build 
```
fixed the issue - flutter sdk version changes as it should.
