### ISSUE TITLE
fvm install not working

### ISSUE THREAD

**Issue by burhankhanzada** [fluttertools/fvm#510]
**Before creating a bug report please make check the following**

- [X] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [X] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [X] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [X] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
fvm install not working without sudo
Flutter "stable" is not installed.

Installing version: stable...

**To Reproduce**

1. Go to terminal..
2. Run `fvm install stable --verbose`
5. Check...
6. See error

**Expected behavior**
shoudle be install without sudo command as flutter suggest don't run flutter command as userser
**Logs**
```bash
Installing version: stable...
[     0.000s] FileSystemException: Creation failed, path = '/fvm' (OS Error: Read-only file system, errno = 30)

Could not install stable

Please run command with  --verbose if you want more information
```

**FVM Doctor Output**
```bash
No FVM config found:
/Users/burhankhanzada/Projects/demo_project
Fvm will run the version in your PATH env: null

Configured env paths:
___________________________________________________

Flutter:


Dart:
/opt/homebrew/bin/dart

FVM_HOME:
/fvm
```

**Desktop (please complete the following information):**

- OS: Mac Os 13.2.1
- FVM Version: latest from brew
- If Windows: Which Powershell are you using?

**Comment by akarabach** [comment]
the same for me

**Comment by leoafarias** [comment]
Based on the message it says you don't have permission to write to your local directory.
