### ISSUE TITLE
[BUG] - fvm 2.4.1 doesn't support Dart 2.10.5.

### ISSUE THREAD

**Issue by vfiruz97** [fluttertools/fvm#516]
I am on MacOs 13.2.1
VSCode 1.77.0

**Describtion**
I have an old project which uses flutter 1.22.6
So far I got running by `fvm flutter run` in VSCode terminal. But recently I got the following error when I try to run any command starting with `fvm` in this project directory in the VSCode terminal.
```
 fvm --version
Can't load Kernel binary: Invalid kernel binary format version.
fvm 2.4.1 doesn't support Dart 2.10.5.
```
I run `repair` and reactivate fvm. In the other projects all fvm commands execute well as expected but in this old project throwing this error message.
I tried to run `fvm flutter run` out of the VSCode terminal it runs well.

What is wrong with fvm when running it in the VSCode terminal where opened project set with old flutter version? In my case Flutter 1.22.6.

**Logs**
Can't load Kernel binary: Invalid kernel binary format version.
fvm 2.4.1 doesn't support Dart 2.10.5.

**Desktop (please complete the following information):**

- OS: [iOS 13.2.1]
- FVM Version [2.4.1]

**Additional context**
Here my setings.json
```
"dart.flutterSdkPath": ".fvm/flutter_sdk",
"dart.flutterSdkPaths": ["/Users/vfiruz/fvm/versions"],
// Remove .fvm files from search
"search.exclude": {
 "**/.fvm": true
},
// Remove from file watching
"files.watcherExclude": {
 "**/.fvm": true
},
```

**Comment by urabadigital** [comment]
use an old version of fvm that is compatible

**Comment by leoafarias** [comment]
Take a look at the standalone installation to see if this solves the problem for you
https://fvm.app/docs/getting_started/installation#standalone

**Comment by moak13** [comment]
Hi, I am currently facing the same issue. I want to ask, what is the best approach to getting an FVM version that works with Flutter 2 projects? Thanks.

**Comment by xweiba** [comment]
> Hi, I am currently facing the same issue. I want to ask, what is the best approach to getting an FVM version that works with Flutter 2 projects? Thanks.您好，我目前面临同样的问题。我想问，获得适用于 Flutter 2 项目的 FVM 版本的最佳方法是什么？谢谢。

choco uninstall fvm
choco install fvm --version=2.3.1
flutter pub global activate fvm
fvm use 2.10.5

**Comment by hasanm08** [comment]
use this
``` dart pub global activate fvm 2.3.1 ```
