### ISSUE TITLE
[Feature Request] Add an `--autoInstall` option to fvm

### ISSUE THREAD

**Issue by ronw98** [fluttertools/fvm#538]
First of, fvm is a great tool and really saves a lot of time when dealing with multiple projects or a single project with a long git history and many flutter version changes so thank you for that.

I'm running a CI/CD pipeline on my projects and use fvm to choose the right version of flutter for each project.
But when I change the version of flutter in the `fvm_config.json` file in my project the pipeline gets stuck on `fvm flutter pub get`. Why? Because fvm asks for a confirmation to install the new version of flutter put in the config file. 

My pipeline runs on a shell gitlab runner so I can go onto the machine and manually install the required version of flutter before running the pipeline but doing that is not ideal.

A great add to fvm would be a `--autoInstall` option that skips user confirmation when requiring a version of flutter not yet installed.

**Comment by TabooSun** [comment]
I run this in CI environment:

```sh
fvm install
fvm use
```

As mentioned in the documentation if you run `fvm install -h`
```
fvm install -h
Installs Flutter SDK Version

Usage: fvm install {version}, if no {version} is provided will install version configured in project.
-h, --help          Print this usage information.
-s, --skip-setup    Skips Flutter setup after install

Run "fvm help" to see global options.
```

**Comment by ronw98** [comment]
Thank you very much @TabooSun I don't know how I did not think of that but it definitely solves my problem!
