### ISSUE TITLE
[BUG] Running FVM in Powershell 

### ISSUE THREAD

**Issue by ryanduffyne** [fluttertools/fvm#544]
**Describe the bug**
When running commands with fvm on windows, I get errors "Could not install 3.10.4" but I think it is a file handling issue.  But the command will die off without running the proxy command.  The verbose output tells me that the file already exists.

**To Reproduce**

1. Go to terminal..
2. Run fvm global --verbose
3. pick the already installed version
[     1.793s] Version: 3.10.4 - already installed.
[     1.799s] FileSystemException: Cannot create link to target 'C:\Users\user\fvm\versions\3.10.4', path = 'C:\Users\user\Documents\GitHub\project\.fvm\flutter_sdk' (OS Error: Cannot create a file when that file already exists.
, errno = 183)
[     1.799s] Usage Exception: Seems you don't have the required permissions on C:\Users\user\fvm On Windows FVM requires to run as an administrator or turn on developer mode: https://bit.ly/3vxRr2M

**Expected behavior**
I would expect this to ignore that the version is already installed and not cause errors.

**Desktop (please complete the following information):**

- OS: Windows
- FVM Version: 2.4.2
- If Windows: Which Powershell are you using? 5.1.19041.3031

**Additional context**
Where dying off becomes a problem is in powershell scripts.  If I script a proxy to a flutter command and it dies with the file exists error from fvm the flutter proxied command does not run.

**Comment by leoafarias** [comment]
@ryanduffyne you need the permissions to create the symlink in order to link the cached version to the global fvm directory.
