### ISSUE TITLE
Remote branch 1.9.1+hotfix.6 not found in upstream origin

### ISSUE THREAD

**Issue by aaongr** [fluttertools/fvm#545]
Hello,
I try to install the flutter ver 1.9.1+hotfix.6
`fvm install 1.9.1+hotfix.6`
 and I get the following message:
> Installing version: 1.9.1+hotfix.6...
> Cloning into '/Users/aaon/fvm/versions/1.9.1+hotfix.6'...
> fatal: Remote branch 1.9.1+hotfix.6 not found in upstream origin
> Could not install 1.9.1+hotfix.6

This specific version exists in the `fvm releases`
> Sep 20 19  │ v1.9.1+hotfix.2
Sep 22 19  │ v1.9.1+hotfix.2
Sep 25 19  │ v1.10.6
Sep 26 19  │ v1.9.1+hotfix.3
Sep 27 19  │ v1.9.1+hotfix.4
Oct 1 19   │ v1.9.1+hotfix.4
Oct 2 19   │ v1.10.7
Oct 4 19   │ v1.10.8
Oct 4 19   │ v1.10.9
Oct 4 19   │ v1.10.10
Oct 4 19   │ v1.10.11
Oct 4 19   │ v1.10.12
Oct 8 19   │ v1.10.13
Oct 8 19   │ v1.10.14
Oct 10 19  │ v1.10.7
Oct 17 19  │ v1.9.1+hotfix.5
Oct 23 19  │ v1.9.1+hotfix.6
Nov 7 19   │ v1.10.15

Why is this happening?
How can I install this ver?

Thank you very much for your kind help and support

**Comment by nirwannursabda** [comment]
it's also happened to me. please help

![Screenshot_197](https://github.com/fluttertools/fvm/assets/8143309/42805ea7-1811-44b9-8cef-8ffc1d710f55)

**Comment by leoafarias** [comment]
You have to add v in front of it as that is the version for much older versions

**Comment by aaongr** [comment]
Great!
Thank you :)
