### ISSUE TITLE
[BUG] Brew install

### ISSUE THREAD

**Issue by handgull** [fluttertools/fvm#555]
Maybe it's not a fvm related bug but when i try to install fvm via brew install i receive this error message:
The following formula cannot be installed from bottle and must be
built from source.
i have already installed gcc but it doesn't work!
Sorry if this is not the right section

**Comment by sbergmair** [comment]
Same here:
Error
```
Cloning into '/opt/homebrew/Library/Taps/leofarias/homebrew-fvm'...
Username for 'https://github.com': XYZ
Password for 'XYZ@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/leofarias/homebrew-fvm/' not found
Error: Failure while executing; `git clone https://github.com/leofarias/homebrew-fvm /opt/homebrew/Library/Taps/leofarias/homebrew-fvm --origin=origin --template= --config core.fsmonitor=false` exited with 128.
```

**Comment by leoafarias** [comment]
@sbergmair can you display the command you are running, this repository seems incorrect leofarias/homebrew-fvm

**Comment by sbergmair** [comment]
I ran the commands on getting started from the website 
```
brew tap leoafarias/fvm
brew install fvm
```

Are these docs old and I should run following instead?

```
brew tap fluttertools/fvm
brew install fvm
```

**Comment by leoafarias** [comment]
@sbergmair No its still the first option. I think what might have happened is that you had a typo on `brew tap leoafarias/fvm` and actually typed `brew tap leofarias/fvm`

**Comment by sbergmair** [comment]
You're right. Typo in my command
Thanks for your help
Can be closed from my side ;)
